### ISSUE TITLE
Integrate more tightly with UI

### ISSUE THREAD

**Issue by getthemike** [danielbayley/atom-gitkraken#1]
Why not make gitkraken launch in a windowed or full mode (maybe with context menu) when clicking or hovering the branch info here:
![image](https://cloud.githubusercontent.com/assets/697694/15491491/e5a5b662-213e-11e6-9baf-ad22d05f48e2.png)

**Comment by danielbayley** [comment]
I'll look into it when I get chance. PR welcome in the mean time 😉
